routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\Controller;
use App\Http\Controllers\HistoricPriceController;
use App\Http\Controllers\PortfolioController;
use App\Http\Controllers\SymbolController;
use App\Http\Controllers\TransactionController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['headers'])->group(function () {
    Route::get('/', [Controller::class, 'viewHome'])->name('home');

    Route::prefix('auth')->name('auth.')->group(function () {
        Route::prefix('forgot-password')->group(function () {
            Route::post('', [AuthController::class, 'sendPasswordReset']);
            Route::get('', [AuthController::class, 'viewForgotPasswordPage'])->name('forgot-password');
        });
        Route::prefix('set-password')->group(function () {
            Route::post('', [AuthController::class, 'setPassword']);
            Route::get('', [AuthController::class, 'viewSetPasswordPage'])->name('set-password');
        });
        Route::prefix('login')->group(function () {
            Route::post('', [AuthController::class, 'login']);
            Route::get('', [AuthController::class, 'viewLoginPage'])->name('login');
        });
        Route::prefix('logout')->name('logout')->group(function () {
            Route::get('', [AuthController::class, 'logout']);
        });
    });

    Route::middleware(['auth'])->group(function () {
        Route::prefix('portfolio')->name('portfolio.')->group(function () {
            Route::prefix('delete')->name('delete')->group(function () {
                Route::get('{id}', [PortfolioController::class, 'deletePortfolio']);
            });
            Route::prefix('manage')->name('manage')->group(function () {
                Route::get('{id}', [PortfolioController::class, 'getManagePortfolio']);
            });
            Route::prefix('update')->name('update')->group(function () {
                Route::post('{id}', [PortfolioController::class, 'updatePortfolio']);
            });
            Route::prefix('create')->group(function () {
                Route::post('', [PortfolioController::class, 'createPortfolio']);
                Route::get('', [PortfolioController::class, 'getCreatePortfolio'])->name('create');
            });
            Route::get('', [PortfolioController::class, 'viewPortfolio'])->name('overview');
        });
        Route::prefix('symbol')->name('symbol.')->group(function () {
            Route::prefix('toggle-position')->name('position')->group(function () {
                Route::get('{id}', [SymbolController::class, 'togglePosition']);
            });
            Route::prefix('remove')->name('remove')->group(function () {
                Route::get('{id}', [SymbolController::class, 'removeSymbol']);
            });
            Route::prefix('edit')->name('edit')->group(function () {
                Route::post('{id}', [SymbolController::class, 'editSymbol']);
            });
            Route::prefix('create')->name('create')->group(function () {
                Route::post('{portfolioId}', [SymbolController::class, 'createSymbol']);
            });
            Route::prefix('view')->name('view')->group(function () {
                Route::prefix('closed')->name('.closed')->group(function () {
                    Route::get('{id}', [SymbolController::class, 'viewClosedSymbol']);
                });
                Route::prefix('open')->name('.open')->group(function () {
                    Route::get('{id}', [SymbolController::class, 'viewOpenSymbol']);
                });
            });
        });
        Route::prefix('transaction')->name('transaction.')->group(function () {
            Route::prefix('remove')->name('remove')->group(function () {
                Route::get('{id}', [TransactionController::class, 'removeTransaction']);
            });
            Route::prefix('edit')->group(function () {
                Route::post('{id}', [TransactionController::class, 'editTransaction']);
                Route::get('{id}', [TransactionController::class, 'getEditTransaction'])->name('edit');
            });
            Route::prefix('view')->name('view')->group(function () {
                Route::get('{id}', [TransactionController::class, 'viewTransaction']);
            });
            Route::prefix('create')->group(function () {
                Route::post('{symbolId}', [TransactionController::class, 'createTransaction']);
                Route::get('{symbolId}', [TransactionController::class, 'getCreateTransaction'])->name('create');
            });
        });
        Route::prefix('historic-price')->name('historic-price.')->group(function () {
            Route::prefix('remove')->name('remove')->group(function () {
                Route::get('{id}', [HistoricPriceController::class, 'removeHistoricPrice']);
            });
            Route::prefix('edit')->group(function () {
                Route::post('{id}', [HistoricPriceController::class, 'editHistoricPrice']);
                Route::get('{id}', [HistoricPriceController::class, 'getEditHistoricPrice'])->name('edit');
            });
            Route::prefix('create')->group(function () {
                Route::post('{symbolId}', [HistoricPriceController::class, 'createHistoricPrice']);
                Route::get('{symbolId}', [HistoricPriceController::class, 'getCreateHistoricPrice'])->name('create');
            });
        });
    });
});

app/Models/Portfolio.php
<?php

namespace App\Models;

use App\Helpers\PQCache;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;

/**
 * @property int $id
 * @property int $user_id
 * @property string $name
 * @property string $type
 * @property string $colour
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property Carbon|null $deleted_at
 */
class Portfolio extends Model
{
    use SoftDeletes;
    use HasFactory;

    protected $appends = [
        'total_cost',
        'total_quantity',
    ];

    /**
     * @return BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    /**
     * @return HasMany
     */
    public function symbols(): HasMany
    {
        return $this->hasMany(Symbol::class, 'portfolio_id');
    }

    /**
     * @return float
     */
    protected function getTotalCostAttribute(): float
    {
        return PQCache::retrieveFromCache('portfolios', $this->id, 'total_cost', function () {
            $total = 0;
            foreach ($this->symbols as $symbol) {
                $total += $symbol->total_cost;
            }

            return $total;
        });
    }

    /**
     * @return float
     */
    protected function getTotalQuantityAttribute(): float
    {
        return PQCache::retrieveFromCache('portfolios', $this->id, 'total_quantity', function () {
            return DB::table((new Transaction())->getTable())->selectRaw('SUM(quantity) as total_quantity')->whereIn('symbol_id', $this->symbols()->pluck('id')->toArray())->whereNull('deleted_at')->first()->total_quantity ?? 0;
        });
    }
}

app/Http/Controllers/PortfolioController.php
<?php

namespace App\Http\Controllers;

use App\Helpers\PQCache;
use App\Jobs\PortfolioPostDeleteJob;
use App\Models\Portfolio;
use App\Models\Symbol;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PortfolioController extends Controller
{
    /* ==============
     * Portfolio Pages
     * ==============
     */

    /**
     * Get the Portfolio Overview page.
     *
     * @param  Request  $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    protected function viewPortfolio(Request $request)
    {
        //All Portfolios
        $portfolios = Portfolio::where('user_id', Auth::id())->get();

        //Account Totals (Cost & Quantity)
        $totals = [
            'cost' => 0,
            'quantity' => 0,
        ];

        foreach ($portfolios as $portfolio) {
            $totals['cost'] += $portfolio->total_cost;
            $totals['quantity'] += $portfolio->total_quantity;
        }
        $totals['cost'] = number_format($totals['cost'], 2);
        $totals['quantity'] = number_format($totals['quantity'], 2);

        //All Symbols
        $symbols = Symbol::with(['portfolio', 'historicPrices'])->where('is_closed', 0)->whereIn('portfolio_id', $portfolios->pluck('id')->toArray())->get();

        //->Next 3 by next date
        $next3 = $symbols->whereNotNull('next_price_date')->sortBy('next_price_date')->take(3);

        //->All grouped by portfolio
        $symbols = $symbols->groupBy('portfolio_id');

        //Closed Symbols
        $closed = Symbol::with(['portfolio', 'historicPrices'])->where('is_closed', 1)->whereIn('portfolio_id', $portfolios->pluck('id')->toArray())->get();

        return view('dashboard.portfolio.overview', ['portfolios' => $portfolios, 'totals' => $totals, 'symbols' => $symbols, 'next3' => $next3, 'closed' => $closed]);
    }

    /**
     * Get the Create Portfolio page.
     *
     * @param  Request  $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    protected function getCreatePortfolio(Request $request)
    {
        return view('dashboard.portfolio.create', ['portfolio' => new Portfolio()]);
    }

    /**
     * Create the portfolio.
     *
     * @param  Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    protected function createPortfolio(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'type' => 'required',
            'colour' => 'required',
        ]);

        //Create Portfolio
        /** @var Portfolio */
        $portfolio = new Portfolio();
        $portfolio->name = $request->input('name');
        $portfolio->type = $request->input('type');
        $portfolio->colour = $request->input('colour');
        $portfolio->user_id = Auth::id();

        if ($portfolio->save()) {
            return redirect()->route('portfolio.overview')->with('success', 'Portfolio created');
        } else {
            return redirect()->back()->with('error', 'Could not save portfolio');
        }
    }

    /**
     * Get the Manage Portfolio page.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    protected function getManagePortfolio(Request $request, int $id)
    {
        $portfolio = Portfolio::with(['symbols'])->find($id);
        if (is_null($portfolio)) {
            abort(404);
        }

        return view('dashboard.portfolio.manage', ['portfolio' => $portfolio]);
    }

    /**
     * Update the portfolio.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    protected function updatePortfolio(Request $request, int $id)
    {
        $request->validate([
            'name' => 'required',
            'type' => 'required',
            'colour' => 'required',
        ]);

        //Get Portfolio
        /** @var Portfolio|null $portfolio */
        $portfolio = Portfolio::find($id);
        if (is_null($portfolio)) {
            return redirect()->back()->with('error', 'Portfolio Not Found');
        }

        $portfolio->name = $request->input('name');
        $portfolio->type = $request->input('type');
        $portfolio->colour = $request->input('colour');

        if ($portfolio->save()) {
            return redirect()->route('portfolio.manage', ['id' => $portfolio->id])->with('success', 'Portfolio updated');
        } else {
            return redirect()->back()->with('error', 'Could not save portfolio');
        }
    }

    /**
     * Delete the portfolio.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    protected function deletePortfolio(Request $request, int $id)
    {
        //Get Portfolio
        /** @var Portfolio|null $portfolio */
        $portfolio = Portfolio::find($id);
        if (is_null($portfolio)) {
            return redirect()->back()->with('error', 'Portfolio Not Found');
        }

        if ($portfolio->delete()) {
            PortfolioPostDeleteJob::dispatch($portfolio->id)->onQueue('long');
            PQCache::removeFromCache('portfolios', $portfolio->id);

            return redirect()->route('portfolio.overview')->with('success', 'Portfolio deleted');
        } else {
            return redirect()->back()->with('error', 'Could not delete portfolio');
        }
    }
}

resources/views/dashboard/portfolio/components/portfolio-delete.blade.php
<div class="mx-4 grid md:grid-cols-3 gap-6">
    <div class="md:col-start-1 md:col-end-2">
        <p class="text-lg text-neutral-800 dark:text-neutral-300">Delete Portfolio</p>
        <p class="text-sm text-neutral-500 dark:text-neutral-400 mt-2">If you no longer need this portfolio you can delete it here, this will also delete all symbols, transactions and historic prices that are present in this portfolio.</p>
    </div>
    <div class="md:col-start-2 md:col-end-4">
        <div class="flex justify-end items-end h-full">
            <a href="{{ route('portfolio.delete', ['id' => $portfolio->id]) }}" id="portfolio-delete-button" class="px-3 py-2 rounded-md text-sm font-medium text-error-500 hover:bg-error-100 dark:hover:bg-error-700 dark:hover:text-error-300">Delete Portfolio</a>
        </div>
    </div>
</div>
<hr class="mx-4 mt-8 border border-neutral-200 dark:border-neutral-700">

resources/views/dashboard/portfolio/components/portfolio-details.blade.php
<div class="mx-4 grid md:grid-cols-3 gap-6">
    <div class="md:col-start-1 md:col-end-2">
        <p class="text-lg text-neutral-800 dark:text-neutral-300">Portfolio Details</p>
        <p class="text-sm text-neutral-500 dark:text-neutral-400 mt-2">You can change any of the portfolio settings here, this includes the name, type and colour.</p>
    </div>
    <div class="md:col-start-2 md:col-end-4">
        <form action="{{ $action }}" method="post">
            @csrf
            <div class="space-y-4 mx-auto">
                <div>
                    <label for="name" class="block text-sm font-medium text-neutral-700 dark:text-neutral-400">Name</label>
                    <div class="mt-1 flex rounded-md">
                        <input type="text" name="name" id="name" class="focus:ring-primary-500 focus:border-primary-500 flex-1 block w-full rounded text-sm border-neutral-300 dark:bg-neutral-800 dark:text-neutral-300 dark:border-neutral-600" value="{{ $portfolio->name }}">
                    </div>
                </div>
                <div>
                    <label for="type" class="block text-sm font-medium text-neutral-700 dark:text-neutral-400">Type</label>
                    <div class="mt-1 flex rounded-md">
                        <select name="type" id="type" class="focus:ring-primary-500 focus:border-primary-500 flex-1 block w-full rounded text-sm border-neutral-300 dark:bg-neutral-800 dark:text-neutral-300 dark:border-neutral-600">
                            <option value="dealing" @if($portfolio->type == 'dealing') selected @endif>Dealing</option>
                            <option value="isa" @if($portfolio->type == 'isa') selected @endif>ISA</option>
                            <option value="sipp" @if($portfolio->type == 'sipp') selected @endif>SIPP</option>
                        </select>
                    </div>
                </div>
                <div>
                    <label for="colour" class="block text-sm font-medium text-neutral-700 dark:text-neutral-400">Colour</label>
                    <div class="mt-1 flex rounded-md">
                        <select name="colour" id="colour" class="focus:ring-primary-500 focus:border-primary-500 flex-1 block w-full rounded text-sm border-neutral-300 dark:bg-neutral-800 dark:text-neutral-300 dark:border-neutral-600">
                            <option value="blueGray" @if($portfolio->colour == 'blueGray') selected @endif>Blue Gray</option>
                            <option value="coolGray" @if($portfolio->colour == 'coolGray') selected @endif>Cool Gray</option>
                            <option value="gray" @if($portfolio->colour == 'gray') selected @endif>Gray</option>
                            <option value="trueGray" @if($portfolio->colour == 'trueGray') selected @endif>True Gray</option>
                            <option value="warmGray" @if($portfolio->colour == 'warmGray') selected @endif>Warm Gray</option>
                            <option value="red" @if($portfolio->colour == 'red') selected @endif>Red</option>
                            <option value="orange" @if($portfolio->colour == 'orange') selected @endif>Orange</option>
                            <option value="amber" @if($portfolio->colour == 'amber') selected @endif>Amber</option>
                            <option value="yellow" @if($portfolio->colour == 'yellow') selected @endif>Yellow</option>
                            <option value="lime" @if($portfolio->colour == 'lime') selected @endif>Lime</option>
                            <option value="green" @if($portfolio->colour == 'green') selected @endif>Green</option>
                            <option value="emerald" @if($portfolio->colour == 'emerald') selected @endif>Emerald</option>
                            <option value="teal" @if($portfolio->colour == 'teal') selected @endif>Teal</option>
                            <option value="cyan" @if($portfolio->colour == 'cyan') selected @endif>Cyan</option>
                            <option value="lightBlue" @if($portfolio->colour == 'lightBlue') selected @endif>Light Blue</option>
                            <option value="blue" @if($portfolio->colour == 'blue') selected @endif>Blue</option>
                            <option value="indigo" @if($portfolio->colour == 'indigo') selected @endif>Indigo</option>
                            <option value="violet" @if($portfolio->colour == 'violet') selected @endif>Violet</option>
                            <option value="purple" @if($portfolio->colour == 'purple') selected @endif>Purple</option>
                            <option value="fuchsia" @if($portfolio->colour == 'fuchsia') selected @endif>Fuchsia</option>
                            <option value="pink" @if($portfolio->colour == 'pink') selected @endif>Pink</option>
                            <option value="rose" @if($portfolio->colour == 'rose') selected @endif>Rose</option>
                        </select>
                    </div>
                </div>
                <div>
                    <div class="text-right pt-2">
                        <button type="submit" class="px-3 py-2 rounded-md text-sm font-medium text-primary-800 bg-primary-200 hover:bg-primary-300 w-full md:w-auto dark:bg-primary-800 dark:text-primary-500 dark:hover:bg-primary-900">Save</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<hr class="mx-4 mt-8 border border-neutral-200 dark:border-neutral-700">

resources/views/dashboard/portfolio/components/portfolio-symbols.blade.php
<div class="mx-4 grid md:grid-cols-3 gap-6">
    <div class="md:col-start-1 md:col-end-2">
        <p class="text-lg text-neutral-800 dark:text-neutral-300">Symbols</p>
        <p class="text-sm text-neutral-500 dark:text-neutral-400 mt-2">You can add & update any symbols that belong to this portfolio.</p>
    </div>
    <div class="md:col-start-2 md:col-end-4">
        <div class="text-right">
            <button id="portfolio-add-symbol-button" class="px-3 py-2 rounded-md text-sm font-medium text-neutral-800 bg-neutral-200 hover:bg-neutral-300 dark:hover:bg-neutral-600 dark:text-neutral-300 dark:bg-neutral-700">Add</button>
        </div>
        <div class="hidden" id="portfolio-symbol-new">
            <div class="mt-6">
                <div class="bg-white dark:bg-neutral-900 rounded-lg shadow-lg">
                    <div class="p-4">
                        <div class="flex justify-between items-center">
                            <p class="text-lg text-neutral-600 dark:text-neutral-400">New Symbol</p>
                        </div>
                    </div>
                    <div class="p-4 bg-neutral-100 dark:bg-neutral-800">
                        <div>
                            <form action="{{ route('symbol.create', ['portfolioId' => $portfolio->id]) }}" class="grid md:grid-cols-2 gap-4" method="post">
                                @csrf
                                <div class="md:col-start-1 md:col-end-3">
                                    <div class="rounded-md">
                                        <input type="text" name="name" id="symbols.name.new" class="focus:ring-neutral-500 focus:border-neutral-500 block w-full rounded text-sm border-neutral-300 dark:bg-neutral-800 dark:text-neutral-300 dark:border-neutral-600" placeholder="Symbol Name">
                                    </div>
                                </div>
                                <div>
                                    <div class="rounded-md">
                                        <input type="text" name="ticker" id="symbols.ticker.new" class="focus:ring-neutral-500 focus:border-neutral-500 block w-full rounded text-sm border-neutral-300 dark:bg-neutral-800 dark:text-neutral-300 dark:border-neutral-600" placeholder="Symbol Ticker">
                                    </div>
                                </div>
                                <div>
                                    <div class="rounded-md">
                                        <input type="text" name="index" id="symbols.index.new" class="focus:ring-neutral-500 focus:border-neutral-500 block w-full rounded text-sm border-neutral-300 dark:bg-neutral-800 dark:text-neutral-300 dark:border-neutral-600" placeholder="Symbol Index">
                                    </div>
                                </div>
                                <div class="md:col-start-1 md:col-end-3 md:flex justify-end items-center">
                                    <button type="submit" class="px-3 py-2 rounded-md text-sm font-medium text-primary-800 bg-primary-200 hover:bg-primary-300 w-full md:w-auto dark:bg-primary-800 dark:text-primary-500 dark:hover:bg-primary-900">Save</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="portfolio-symbol-outer">
            @foreach($portfolio->symbols as $key => $symbol)
                <div class="mt-6 portfolio-symbol">
                    <div class="bg-white dark:bg-neutral-900 rounded-lg shadow-lg">
                        <div class="p-4 symbol-accordion cursor-pointer" data-selector="{{ $key }}">
                            <div class="flex justify-between items-center">
                                <p class="text-lg text-neutral-600 dark:text-neutral-400">{{ $symbol->name }}</p>
                                <em class="fas fa-chevron-down text-neutral-500 dark:text-neutral-400 symbol-accordion-icon" data-icon="{{ $key }}"></em>
                            </div>
                        </div>
                        <div class="p-4 bg-neutral-100 dark:bg-neutral-800 hidden symbol-accordion-form" data-form="{{ $key }}">
                            <div>
                                <form action="{{ route('symbol.edit', ['id' => $symbol->id]) }}" class="grid md:grid-cols-2 gap-4" method="post">
                                    @csrf
                                    <div class="md:col-start-1 md:col-end-3">
                                        <div class="rounded-md">
                                            <input type="text" name="name" id="symbols.name.{{ $key }}" class="focus:ring-neutral-500 focus:border-neutral-500 block w-full rounded text-sm border-neutral-300 dark:bg-neutral-800 dark:text-neutral-300 dark:border-neutral-600" placeholder="Symbol Name" value="{{ $symbol->name }}">
                                        </div>
                                    </div>
                                    <div>
                                        <div class="rounded-md">
                                            <input type="text" name="ticker" id="symbols.ticker.{{ $key }}" class="focus:ring-neutral-500 focus:border-neutral-500 block w-full rounded text-sm border-neutral-300 dark:bg-neutral-800 dark:text-neutral-300 dark:border-neutral-600" placeholder="Symbol Ticker" value="{{ $symbol->ticker }}">
                                        </div>
                                    </div>
                                    <div>
                                        <div class="rounded-md">
                                            <input type="text" name="index" id="symbols.index.{{ $key }}" class="focus:ring-neutral-500 focus:border-neutral-500 block w-full rounded text-sm border-neutral-300 dark:bg-neutral-800 dark:text-neutral-300 dark:border-neutral-600" placeholder="Symbol Index" value="{{ $symbol->index }}">
                                        </div>
                                    </div>
                                    <div class="md:col-span-2">
                                        <a href="{{ route('symbol.remove', ['id' => $symbol->id]) }}" class="px-3 py-2 rounded-md text-sm font-medium text-error-500 hover:bg-error-100 dark:hover:bg-error-700 dark:hover:text-error-300 float-left">Delete</a>
                                        <a href="{{ route('symbol.position', ['id' => $symbol->id]) }}" class="px-3 py-2 ml-2 rounded-md text-sm font-medium text-info-500 hover:bg-info-100 dark:hover:bg-info-700 dark:hover:text-info-300 float-left">{{ $symbol->is_closed ? 'Re-open Symbol':'Close Symbol' }}</a>
                                        <button type="submit" class="px-3 py-2 rounded-md text-sm font-medium text-neutral-500 hover:bg-neutral-200 float-right dark:hover:bg-neutral-900 dark:text-neutral-300">Save</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
</div>
<hr class="mx-4 mt-8 border border-neutral-200 dark:border-neutral-700">