routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\Controller;
use App\Http\Controllers\HistoricPriceController;
use App\Http\Controllers\PortfolioController;
use App\Http\Controllers\SymbolController;
use App\Http\Controllers\TransactionController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['headers'])->group(function () {
    Route::get('/', [Controller::class, 'viewHome'])->name('home');

    Route::prefix('auth')->name('auth.')->group(function () {
        Route::prefix('forgot-password')->group(function () {
            Route::post('', [AuthController::class, 'sendPasswordReset']);
            Route::get('', [AuthController::class, 'viewForgotPasswordPage'])->name('forgot-password');
        });
        Route::prefix('set-password')->group(function () {
            Route::post('', [AuthController::class, 'setPassword']);
            Route::get('', [AuthController::class, 'viewSetPasswordPage'])->name('set-password');
        });
        Route::prefix('login')->group(function () {
            Route::post('', [AuthController::class, 'login']);
            Route::get('', [AuthController::class, 'viewLoginPage'])->name('login');
        });
        Route::prefix('logout')->name('logout')->group(function () {
            Route::get('', [AuthController::class, 'logout']);
        });
    });

    Route::middleware(['auth'])->group(function () {
        Route::prefix('portfolio')->name('portfolio.')->group(function () {
            Route::prefix('delete')->name('delete')->group(function () {
                Route::get('{id}', [PortfolioController::class, 'deletePortfolio']);
            });
            Route::prefix('manage')->name('manage')->group(function () {
                Route::get('{id}', [PortfolioController::class, 'getManagePortfolio']);
            });
            Route::prefix('update')->name('update')->group(function () {
                Route::post('{id}', [PortfolioController::class, 'updatePortfolio']);
            });
            Route::prefix('create')->group(function () {
                Route::post('', [PortfolioController::class, 'createPortfolio']);
                Route::get('', [PortfolioController::class, 'getCreatePortfolio'])->name('create');
            });
            Route::get('', [PortfolioController::class, 'viewPortfolio'])->name('overview');
        });
        Route::prefix('symbol')->name('symbol.')->group(function () {
            Route::prefix('toggle-position')->name('position')->group(function () {
                Route::get('{id}', [SymbolController::class, 'togglePosition']);
            });
            Route::prefix('remove')->name('remove')->group(function () {
                Route::get('{id}', [SymbolController::class, 'removeSymbol']);
            });
            Route::prefix('edit')->name('edit')->group(function () {
                Route::post('{id}', [SymbolController::class, 'editSymbol']);
            });
            Route::prefix('create')->name('create')->group(function () {
                Route::post('{portfolioId}', [SymbolController::class, 'createSymbol']);
            });
            Route::prefix('view')->name('view')->group(function () {
                Route::prefix('closed')->name('.closed')->group(function () {
                    Route::get('{id}', [SymbolController::class, 'viewClosedSymbol']);
                });
                Route::prefix('open')->name('.open')->group(function () {
                    Route::get('{id}', [SymbolController::class, 'viewOpenSymbol']);
                });
            });
        });
        Route::prefix('transaction')->name('transaction.')->group(function () {
            Route::prefix('remove')->name('remove')->group(function () {
                Route::get('{id}', [TransactionController::class, 'removeTransaction']);
            });
            Route::prefix('edit')->group(function () {
                Route::post('{id}', [TransactionController::class, 'editTransaction']);
                Route::get('{id}', [TransactionController::class, 'getEditTransaction'])->name('edit');
            });
            Route::prefix('view')->name('view')->group(function () {
                Route::get('{id}', [TransactionController::class, 'viewTransaction']);
            });
            Route::prefix('create')->group(function () {
                Route::post('{symbolId}', [TransactionController::class, 'createTransaction']);
                Route::get('{symbolId}', [TransactionController::class, 'getCreateTransaction'])->name('create');
            });
        });
        Route::prefix('historic-price')->name('historic-price.')->group(function () {
            Route::prefix('remove')->name('remove')->group(function () {
                Route::get('{id}', [HistoricPriceController::class, 'removeHistoricPrice']);
            });
            Route::prefix('edit')->group(function () {
                Route::post('{id}', [HistoricPriceController::class, 'editHistoricPrice']);
                Route::get('{id}', [HistoricPriceController::class, 'getEditHistoricPrice'])->name('edit');
            });
            Route::prefix('create')->group(function () {
                Route::post('{symbolId}', [HistoricPriceController::class, 'createHistoricPrice']);
                Route::get('{symbolId}', [HistoricPriceController::class, 'getCreateHistoricPrice'])->name('create');
            });
        });
    });
});

app/Models/Symbol.php
<?php

namespace App\Models;

use App\Helpers\PQCache;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;

/**
 * @property int $id
 * @property int $portfolio_id
 * @property string $name
 * @property string $ticker
 * @property string $index
 * @property bool $is_closed
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property Carbon|null $deleted_at
 */
class Symbol extends Model
{
    use SoftDeletes;
    use HasFactory;

    /**
     * Get the portfolio the Symbol belongs to.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function portfolio()
    {
        return $this->belongsTo(Portfolio::class, 'portfolio_id');
    }

    /**
     * Get the transactions the Symbol has.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function transactions()
    {
        return $this->hasMany(Transaction::class, 'symbol_id')->orderBy('buy_date', 'desc');
    }

    /**
     * Get the historic prices the Symbol has.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function historicPrices()
    {
        return $this->hasMany(HistoricPrice::class, 'symbol_id')->orderBy('date', 'desc');
    }

    /**
     * Get the total amount of money spent for this symbol (including charges & tax).
     *
     * @return float
     */
    public function getTotalCostAttribute()
    {
        return PQCache::retrieveFromCache('symbols', $this->id, 'total_cost', function () {
            if ($this->total_quantity == 0) {
                return 0;
            }

            return DB::table((new Transaction())->getTable())->selectRaw('SUM((quantity * buy_price) + charges + tax + adjustment) as total_cost')->where('symbol_id', $this->id)->whereNull('deleted_at')->first()->total_cost ?? 0;
        });
    }

    /**
     * Get the total quantity held.
     *
     * @return float
     */
    public function getTotalQuantityAttribute()
    {
        return PQCache::retrieveFromCache('symbols', $this->id, 'total_quantity', function () {
            return DB::table((new Transaction())->getTable())->selectRaw('SUM(quantity) as total_quantity')->where('symbol_id', $this->id)->whereNull('deleted_at')->first()->total_quantity ?? 0;
        });
    }

    /**
     * Get the total amount of money spent for this symbol (excluding charges & tax).
     *
     * @return int|mixed
     */
    public function getTotalConsiderationAttribute()
    {
        return PQCache::retrieveFromCache('symbols', $this->id, 'total_consideration', function () {
            return DB::table((new Transaction())->getTable())->selectRaw('SUM(quantity * buy_price) as total_consideration')->where('symbol_id', $this->id)->whereNull('deleted_at')->first()->total_consideration ?? 0;
        });
    }

    /**
     * Get the latest historic price for the symbol.
     *
     * @return Model|\Illuminate\Database\Eloquent\Relations\HasMany|object|null
     */
    public function getLatestPriceAttribute()
    {
        return PQCache::retrieveFromCache('symbols', $this->id, 'latest_price', function () {
            return $this->historicPrices()->latest('date')->first();
        });
    }

    /**
     * Get the next date we need a historic price for the symbol.
     *
     * @return Carbon|null
     */
    public function getNextPriceDateAttribute()
    {
        return PQCache::retrieveFromCache('symbols', $this->id, 'next_price_date', function () {
            return $this->latest_price?->date->addMonths(6);
        });
    }

    /**
     * Get the total sale amount based on the latest pricing.
     *
     * @return float|int
     */
    public function getTotalSaleAttribute()
    {
        return PQCache::retrieveFromCache('symbols', $this->id, 'total_sale', function () {
            return isset($this->latest_price) ? $this->latest_price->close_price * $this->total_quantity : 0;
        });
    }

    /**
     * Get the gross roi of a symbol.
     *
     * @return mixed
     */
    public function getGrossRoiAttribute()
    {
        return PQCache::retrieveFromCache('symbols', $this->id, 'gross_roi', function () {
            return $this->total_sale - $this->total_consideration;
        });
    }

    /**
     * Get the gross roi percentage of a symbol.
     *
     * @return float|int
     */
    public function getGrossRoiPercentageAttribute()
    {
        return PQCache::retrieveFromCache('symbols', $this->id, 'gross_roi_percentage', function () {
            return $this->total_consideration != 0 ? ($this->gross_roi / $this->total_consideration) * 100 : 0;
        });
    }

    /**
     * Get the net roi of a symbol.
     *
     * @return mixed
     */
    public function getNetRoiAttribute()
    {
        return PQCache::retrieveFromCache('symbols', $this->id, 'net_roi', function () {
            return $this->total_sale - $this->total_cost;
        });
    }

    /**
     * Get the net roi percentage of a symbol.
     *
     * @return float|int
     */
    public function getNetRoiPercentageAttribute()
    {
        return PQCache::retrieveFromCache('symbols', $this->id, 'net_roi_percentage', function () {
            return $this->total_cost != 0 ? ($this->net_roi / $this->total_cost) * 100 : 0;
        });
    }

    /**
     * Get the symbols percentage of total cost compared to the overall portfolio.
     *
     * @return float|int
     */
    public function getPercentageOfPortfolioAttribute()
    {
        return $this->portfolio->total_cost != 0 ? ($this->total_cost / $this->portfolio->total_cost) * 100 : 0;
    }

    /**
     * Get the total profit for this symbol.
     *
     * @return float|int
     */
    public function getTotalProfitAttribute(): float|int
    {
        return PQCache::retrieveFromCache('symbols', $this->id, 'total_profit', function () {
            if (! $this->is_closed) {
                return 0;
            }

            return DB::table((new Transaction())->getTable())->selectRaw('SUM((quantity * buy_price) + charges + tax + adjustment) * -1 as total_profit')->where('symbol_id', $this->id)->whereNull('deleted_at')->first()->total_profit ?? 0;
        });
    }
}

app/Http/Controllers/SymbolController.php
<?php

namespace App\Http\Controllers;

use App\Helpers\PQCache;
use App\Models\Portfolio;
use App\Models\Symbol;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class SymbolController extends Controller
{
    /* ==============
     * Symbol Pages
     * ==============
     */

    /**
     * @param  Request  $request
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    protected function viewOpenSymbol(Request $request, int $id)
    {
        $symbol = Symbol::with(['transactions', 'historicPrices', 'portfolio'])->find($id);
        if (is_null($symbol)) {
            abort(404);
        }

        return view('dashboard.symbol.open', ['symbol' => $symbol]);
    }

    /**
     * @param  Request  $request
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    protected function viewClosedSymbol(Request $request, int $id)
    {
        $symbol = Symbol::with(['transactions', 'historicPrices', 'portfolio'])->find($id);
        if (is_null($symbol)) {
            abort(404);
        }

        return view('dashboard.symbol.closed', ['symbol' => $symbol]);
    }

    /**
     * Create the symbol.
     *
     * @param  Request  $request
     * @param  int  $portfolioId
     * @return \Illuminate\Http\RedirectResponse
     */
    protected function createSymbol(Request $request, int $portfolioId)
    {
        $request->validate([
            'name' => 'required',
            'ticker' => 'required',
            'index' => 'required',
        ]);

        //Create Symbol
        /** @var Symbol */
        $symbol = new Symbol();
        $symbol->name = $request->input('name');
        $symbol->ticker = $request->input('ticker');
        $symbol->index = $request->input('index');
        $symbol->portfolio_id = $portfolioId;

        if ($symbol->save()) {
            return redirect()->route('portfolio.manage', ['id' => $portfolioId])->with('success', 'Symbol created');
        } else {
            return redirect()->back()->with('error', 'Could not save symbol');
        }
    }

    /**
     * Edit the symbol.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    protected function editSymbol(Request $request, int $id)
    {
        $request->validate([
            'name' => 'required',
            'ticker' => 'required',
            'index' => 'required',
        ]);

        //Get Symbol
        /** @var Symbol|null $symbol */
        $symbol = Symbol::find($id);
        if (is_null($symbol)) {
            return redirect()->back()->with('error', 'Symbol Not Found');
        }

        $symbol->name = $request->input('name');
        $symbol->ticker = $request->input('ticker');
        $symbol->index = $request->input('index');

        if ($symbol->save()) {
            return redirect()->route('portfolio.manage', ['id' => $symbol->portfolio_id])->with('success', 'Symbol updated');
        } else {
            return redirect()->back()->with('error', 'Could not save symbol');
        }
    }

    /**
     * Remove the symbol.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    protected function removeSymbol(Request $request, int $id)
    {
        //Get Symbol
        /** @var Symbol|null $symbol */
        $symbol = Symbol::find($id);
        if (is_null($symbol)) {
            return redirect()->back()->with('error', 'Symbol Not Found');
        }

        if ($symbol->delete()) {
            PQCache::removeFromCache('portfolios', $symbol->portfolio_id);
            PQCache::removeFromCache('symbols', $symbol->id);

            return redirect()->route('portfolio.manage', ['id' => $symbol->portfolio_id])->with('success', 'Symbol deleted');
        } else {
            return redirect()->back()->with('error', 'Could not delete symbol');
        }
    }

    protected function togglePosition(Request $request, int $id)
    {
        //Get Symbol
        /** @var Symbol|null $symbol */
        $symbol = Symbol::find($id);
        if (is_null($symbol)) {
            return redirect()->back()->with('error', 'Symbol Not Found');
        }

        $symbol->is_closed = ! $symbol->is_closed;

        if ($symbol->save()) {
            return redirect()->route('portfolio.manage', ['id' => $symbol->portfolio_id])->with('success', 'Symbol updated');
        } else {
            return redirect()->back()->with('error', 'Could not save symbol');
        }
    }
}

resources/views/dashboard/symbol/includes/banner-closed.blade.php
@section('banner')
    <div class="bg-neutral-200 dark:bg-neutral-700" id="banner">
        <div class="container mx-auto">
            <div class="grid">
                <div class="my-8 mx-16 text-center">
                    <p class="font-semibold text-md uppercase tracking-wide text-neutral-500">Name</p>
                    <p class="font-light text-4xl text-neutral-900 dark:text-neutral-200">{{ $symbol->name }}</p>
                </div>
            </div>
            <div class="grid grid-cols-2 md:grid-cols-6 border-t border-neutral-400 dark:border-neutral-500">
                <div class="md:col-start-2 my-8 mx-12 text-center">
                    <p class="font-semibold text-sm uppercase tracking-wide text-neutral-500">Index</p>
                    <p class="font-light text-2xl text-neutral-800 dark:text-neutral-300">{{ $symbol->index }}</p>
                </div>
                <div class="my-8 mx-12 text-center">
                    <p class="font-semibold text-sm uppercase tracking-wide text-neutral-500">Ticker</p>
                    <p class="font-light text-2xl text-neutral-800 dark:text-neutral-300">{{ $symbol->ticker }}</p>
                </div>
                <div class="my-8 mx-12 text-center">
                    <p class="font-semibold text-sm uppercase tracking-wide text-neutral-500">Portfolio</p>
                    <p class="font-light text-2xl text-neutral-800 dark:text-neutral-300">{{ $symbol->portfolio->name }}</p>
                </div>
                <div class="my-8 mx-12 text-center">
                    <p class="font-semibold text-sm uppercase tracking-wide text-neutral-500">Total Profit</p>
                    <p class="font-light text-2xl text-neutral-800 dark:text-neutral-300">&pound;{{ number_format($symbol->total_profit, 2) }}</p>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/symbol/includes/banner-open.blade.php
@section('banner')
    <div class="bg-primary-100 dark:bg-primary-900" id="banner">
        <div class="container mx-auto">
            <div class="grid">
                <div class="my-8 mx-16 text-center">
                    <p class="font-semibold text-md uppercase tracking-wide text-primary-500 dark:text-primary-600">Name</p>
                    <p class="font-light text-4xl text-primary-900 dark:text-primary-100">{{ $symbol->name }}</p>
                </div>
            </div>
            <div class="grid grid-cols-2 md:grid-cols-6 border-t border-primary-400 dark:border-primary-700">
                <div class="my-8 mx-12 text-center">
                    <p class="font-semibold text-sm uppercase tracking-wide text-primary-500 dark:text-primary-600">Index</p>
                    <p class="font-light text-2xl text-primary-800 dark:text-primary-200">{{ $symbol->index }}</p>
                </div>
                <div class="my-8 mx-12 text-center">
                    <p class="font-semibold text-sm uppercase tracking-wide text-primary-500 dark:text-primary-600">Ticker</p>
                    <p class="font-light text-2xl text-primary-800 dark:text-primary-200">{{ $symbol->ticker }}</p>
                </div>
                <div class="my-8 mx-12 text-center">
                    <p class="font-semibold text-sm uppercase tracking-wide text-primary-500 dark:text-primary-600">Portfolio</p>
                    <p class="font-light text-2xl text-primary-800 dark:text-primary-200">{{ $symbol->portfolio->name }}</p>
                </div>
                <div class="my-8 mx-12 text-center">
                    <p class="font-semibold text-sm uppercase tracking-wide text-primary-500 dark:text-primary-600">Total Cost</p>
                    <p class="font-light text-2xl text-primary-800 dark:text-primary-200">&pound;{{ number_format($symbol->total_cost, 2) }}</p>
                </div>
                <div class="my-8 mx-12 text-center">
                    <p class="font-semibold text-sm uppercase tracking-wide text-primary-500 dark:text-primary-600">Quantity Held</p>
                    <p class="font-light text-2xl text-primary-800 dark:text-primary-200">{{ number_format($symbol->total_quantity, 2) }}</p>
                </div>
                <div class="my-8 mx-12 text-center">
                    <p class="font-semibold text-sm uppercase tracking-wide text-primary-500 dark:text-primary-600">&percnt; of Portfolio</p>
                    <p class="font-light text-2xl text-primary-800 dark:text-primary-200">{{ number_format($symbol->percentage_of_portfolio, 2) }}&percnt;</p>
                </div>
            </div>
        </div>
    </div>
@endsection