routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\Controller;
use App\Http\Controllers\HistoricPriceController;
use App\Http\Controllers\PortfolioController;
use App\Http\Controllers\SymbolController;
use App\Http\Controllers\TransactionController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['headers'])->group(function () {
    Route::get('/', [Controller::class, 'viewHome'])->name('home');

    Route::prefix('auth')->name('auth.')->group(function () {
        Route::prefix('forgot-password')->group(function () {
            Route::post('', [AuthController::class, 'sendPasswordReset']);
            Route::get('', [AuthController::class, 'viewForgotPasswordPage'])->name('forgot-password');
        });
        Route::prefix('set-password')->group(function () {
            Route::post('', [AuthController::class, 'setPassword']);
            Route::get('', [AuthController::class, 'viewSetPasswordPage'])->name('set-password');
        });
        Route::prefix('login')->group(function () {
            Route::post('', [AuthController::class, 'login']);
            Route::get('', [AuthController::class, 'viewLoginPage'])->name('login');
        });
        Route::prefix('logout')->name('logout')->group(function () {
            Route::get('', [AuthController::class, 'logout']);
        });
    });

    Route::middleware(['auth'])->group(function () {
        Route::prefix('portfolio')->name('portfolio.')->group(function () {
            Route::prefix('delete')->name('delete')->group(function () {
                Route::get('{id}', [PortfolioController::class, 'deletePortfolio']);
            });
            Route::prefix('manage')->name('manage')->group(function () {
                Route::get('{id}', [PortfolioController::class, 'getManagePortfolio']);
            });
            Route::prefix('update')->name('update')->group(function () {
                Route::post('{id}', [PortfolioController::class, 'updatePortfolio']);
            });
            Route::prefix('create')->group(function () {
                Route::post('', [PortfolioController::class, 'createPortfolio']);
                Route::get('', [PortfolioController::class, 'getCreatePortfolio'])->name('create');
            });
            Route::get('', [PortfolioController::class, 'viewPortfolio'])->name('overview');
        });
        Route::prefix('symbol')->name('symbol.')->group(function () {
            Route::prefix('toggle-position')->name('position')->group(function () {
                Route::get('{id}', [SymbolController::class, 'togglePosition']);
            });
            Route::prefix('remove')->name('remove')->group(function () {
                Route::get('{id}', [SymbolController::class, 'removeSymbol']);
            });
            Route::prefix('edit')->name('edit')->group(function () {
                Route::post('{id}', [SymbolController::class, 'editSymbol']);
            });
            Route::prefix('create')->name('create')->group(function () {
                Route::post('{portfolioId}', [SymbolController::class, 'createSymbol']);
            });
            Route::prefix('view')->name('view')->group(function () {
                Route::prefix('closed')->name('.closed')->group(function () {
                    Route::get('{id}', [SymbolController::class, 'viewClosedSymbol']);
                });
                Route::prefix('open')->name('.open')->group(function () {
                    Route::get('{id}', [SymbolController::class, 'viewOpenSymbol']);
                });
            });
        });
        Route::prefix('transaction')->name('transaction.')->group(function () {
            Route::prefix('remove')->name('remove')->group(function () {
                Route::get('{id}', [TransactionController::class, 'removeTransaction']);
            });
            Route::prefix('edit')->group(function () {
                Route::post('{id}', [TransactionController::class, 'editTransaction']);
                Route::get('{id}', [TransactionController::class, 'getEditTransaction'])->name('edit');
            });
            Route::prefix('view')->name('view')->group(function () {
                Route::get('{id}', [TransactionController::class, 'viewTransaction']);
            });
            Route::prefix('create')->group(function () {
                Route::post('{symbolId}', [TransactionController::class, 'createTransaction']);
                Route::get('{symbolId}', [TransactionController::class, 'getCreateTransaction'])->name('create');
            });
        });
        Route::prefix('historic-price')->name('historic-price.')->group(function () {
            Route::prefix('remove')->name('remove')->group(function () {
                Route::get('{id}', [HistoricPriceController::class, 'removeHistoricPrice']);
            });
            Route::prefix('edit')->group(function () {
                Route::post('{id}', [HistoricPriceController::class, 'editHistoricPrice']);
                Route::get('{id}', [HistoricPriceController::class, 'getEditHistoricPrice'])->name('edit');
            });
            Route::prefix('create')->group(function () {
                Route::post('{symbolId}', [HistoricPriceController::class, 'createHistoricPrice']);
                Route::get('{symbolId}', [HistoricPriceController::class, 'getCreateHistoricPrice'])->name('create');
            });
        });
    });
});

app/Models/HistoricPrice.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * @property int $id
 * @property int $symbol_id
 * @property float $close_price
 * @property float $roi
 * @property string|Carbon $date
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 */
class HistoricPrice extends Model
{
    use HasFactory;

    protected $table = 'historic_prices';

    /**
     * @var string[]
     */
    protected $dates = [
        'date',
    ];

    /**
     * @return BelongsTo
     */
    public function symbol(): BelongsTo
    {
        return $this->belongsTo(Symbol::class, 'symbol_id');
    }

    /**
     * @return float|int
     */
    protected function getRoiPercentageAttribute(): float|int
    {
        return ($this->roi / $this->close_price) * 100;
    }
}

app/Models/Transaction.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @property int $id
 * @property int $symbol_id
 * @property float $quantity
 * @property float $buy_price
 * @property float $charges
 * @property float $tax
 * @property float $adjustment
 * @property string|Carbon $buy_date
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property Carbon|null $deleted_at
 */
class Transaction extends Model
{
    use SoftDeletes;
    use HasFactory;

    /**
     * @var string[]
     */
    protected $dates = [
        'buy_date',
    ];

    /**
     * Get the symbol the Transaction belongs to.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function symbol()
    {
        return $this->belongsTo(Symbol::class, 'symbol_id');
    }

    /**
     * Get the total cost.
     *
     * @return float
     */
    public function getTotalCostAttribute()
    {
        return ($this->quantity * $this->buy_price) + $this->charges + $this->tax + $this->adjustment;
    }

    /**
     * Get the consideration cost.
     *
     * @return float
     */
    public function getConsiderationCostAttribute()
    {
        return $this->quantity * $this->buy_price;
    }
}

app/Http/Controllers/SymbolController.php
<?php

namespace App\Http\Controllers;

use App\Helpers\PQCache;
use App\Models\Portfolio;
use App\Models\Symbol;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class SymbolController extends Controller
{
    /* ==============
     * Symbol Pages
     * ==============
     */

    /**
     * @param  Request  $request
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    protected function viewOpenSymbol(Request $request, int $id)
    {
        $symbol = Symbol::with(['transactions', 'historicPrices', 'portfolio'])->find($id);
        if (is_null($symbol)) {
            abort(404);
        }

        return view('dashboard.symbol.open', ['symbol' => $symbol]);
    }

    /**
     * @param  Request  $request
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    protected function viewClosedSymbol(Request $request, int $id)
    {
        $symbol = Symbol::with(['transactions', 'historicPrices', 'portfolio'])->find($id);
        if (is_null($symbol)) {
            abort(404);
        }

        return view('dashboard.symbol.closed', ['symbol' => $symbol]);
    }

    /**
     * Create the symbol.
     *
     * @param  Request  $request
     * @param  int  $portfolioId
     * @return \Illuminate\Http\RedirectResponse
     */
    protected function createSymbol(Request $request, int $portfolioId)
    {
        $request->validate([
            'name' => 'required',
            'ticker' => 'required',
            'index' => 'required',
        ]);

        //Create Symbol
        /** @var Symbol */
        $symbol = new Symbol();
        $symbol->name = $request->input('name');
        $symbol->ticker = $request->input('ticker');
        $symbol->index = $request->input('index');
        $symbol->portfolio_id = $portfolioId;

        if ($symbol->save()) {
            return redirect()->route('portfolio.manage', ['id' => $portfolioId])->with('success', 'Symbol created');
        } else {
            return redirect()->back()->with('error', 'Could not save symbol');
        }
    }

    /**
     * Edit the symbol.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    protected function editSymbol(Request $request, int $id)
    {
        $request->validate([
            'name' => 'required',
            'ticker' => 'required',
            'index' => 'required',
        ]);

        //Get Symbol
        /** @var Symbol|null $symbol */
        $symbol = Symbol::find($id);
        if (is_null($symbol)) {
            return redirect()->back()->with('error', 'Symbol Not Found');
        }

        $symbol->name = $request->input('name');
        $symbol->ticker = $request->input('ticker');
        $symbol->index = $request->input('index');

        if ($symbol->save()) {
            return redirect()->route('portfolio.manage', ['id' => $symbol->portfolio_id])->with('success', 'Symbol updated');
        } else {
            return redirect()->back()->with('error', 'Could not save symbol');
        }
    }

    /**
     * Remove the symbol.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    protected function removeSymbol(Request $request, int $id)
    {
        //Get Symbol
        /** @var Symbol|null $symbol */
        $symbol = Symbol::find($id);
        if (is_null($symbol)) {
            return redirect()->back()->with('error', 'Symbol Not Found');
        }

        if ($symbol->delete()) {
            PQCache::removeFromCache('portfolios', $symbol->portfolio_id);
            PQCache::removeFromCache('symbols', $symbol->id);

            return redirect()->route('portfolio.manage', ['id' => $symbol->portfolio_id])->with('success', 'Symbol deleted');
        } else {
            return redirect()->back()->with('error', 'Could not delete symbol');
        }
    }

    protected function togglePosition(Request $request, int $id)
    {
        //Get Symbol
        /** @var Symbol|null $symbol */
        $symbol = Symbol::find($id);
        if (is_null($symbol)) {
            return redirect()->back()->with('error', 'Symbol Not Found');
        }

        $symbol->is_closed = ! $symbol->is_closed;

        if ($symbol->save()) {
            return redirect()->route('portfolio.manage', ['id' => $symbol->portfolio_id])->with('success', 'Symbol updated');
        } else {
            return redirect()->back()->with('error', 'Could not save symbol');
        }
    }
}

resources/views/dashboard/symbol/components/historic-prices.blade.php
<div>
    <div class="bg-white dark:bg-neutral-700 shadow-lg rounded-lg w-auto overflow-hidden hidden md:block">
        <table class="w-full divide-y divide-neutral-200 dark:divide-neutral-700" aria-describedby="Historic prices for this symbol">
            <thead class="bg-white dark:bg-neutral-700">
                <tr>
                    <th scope="col" class="px-6 py-4 text-left text-sm font-semibold text-neutral-500 dark:text-neutral-300 uppercase tracking-wide">
                        Date
                    </th>
                    <th scope="col" class="px-6 py-4 text-right text-sm font-semibold text-neutral-500 dark:text-neutral-300 uppercase tracking-wide">
                        Price
                    </th>
                    <th scope="col" class="px-6 py-4 text-right text-sm font-semibold text-neutral-500 dark:text-neutral-300 uppercase tracking-wide">
                        Roi
                    </th>
                    <th scope="col" class="relative px-3 py-4">
                        <span class="sr-only">Edit</span>
                    </th>
                </tr>
            </thead>
            <tbody class="divide-y divide-neutral-200 dark:divide-neutral-700">
                @foreach($historicPrices as $historicPrice)
                    <tr @if($loop->odd) class="bg-neutral-100 dark:bg-neutral-600" @endif>
                        <td class="px-6 py-4 whitespace-nowrap">
                            <p class="font-semibold text-lg text-neutral-600 dark:text-neutral-300">
                                {{ $historicPrice->date->format('jS M Y') }}
                            </p>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap text-right">
                            <p class="font-medium text-neutral-600 dark:text-neutral-300">
                                &pound;{{ number_format($historicPrice->close_price, 2) }}
                            </p>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap text-right">
                            <p class="text-neutral-500 dark:text-neutral-400">
                                {{ number_format($historicPrice->roi_percentage, 2) }}&percnt;
                            </p>
                        </td>

                        <td class="px-3 py-4 whitespace-nowrap text-right">
                            <a href="{{ route('historic-price.edit', ['id' => $historicPrice->id]) }}" class="px-3 py-2 rounded-md text-sm font-medium text-neutral-500 hover:bg-neutral-200 dark:hover:bg-neutral-800 dark:text-neutral-300">Edit</a>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <div class="grid gap-4 block md:hidden">
        @foreach($historicPrices as $historicPrice)
            @include('includes.cards.small', [
                'title' => $historicPrice->date->format('jS M Y'),
                'subtitle' => number_format($historicPrice->roi_percentage, 2) . '%',
                'price' => number_format($historicPrice->close_price, 2),
                'link' => route('historic-price.edit', ['id' => $historicPrice->id]),
                'colour' => $historicPrice->roi_percentage > 0 ? 'lime' : 'gray',
                'belongsTo' => $transaction->id,
            ])
        @endforeach
    </div>
</div>

resources/views/dashboard/symbol/components/transactions.blade.php
<div>
    <div class="bg-white dark:bg-neutral-700 shadow-lg rounded-lg w-auto overflow-hidden hidden md:block">
        <table class="w-full divide-y divide-neutral-200 dark:divide-neutral-700" aria-describedby="Transactions for this symbol">
            <thead class="bg-white dark:bg-neutral-700">
                <tr>
                    <th scope="col" class="px-6 py-4 text-left text-sm font-semibold text-neutral-500 dark:text-neutral-300 uppercase tracking-wide">
                        Date
                    </th>
                    <th scope="col" class="px-6 py-4 text-right text-sm font-semibold text-neutral-500 dark:text-neutral-300 uppercase tracking-wide">
                        Unit Price
                    </th>
                    <th scope="col" class="px-6 py-4 text-right text-sm font-semibold text-neutral-500 dark:text-neutral-300 uppercase tracking-wide">
                        Quantity
                    </th>
                    <th scope="col" class="px-6 py-4 text-right text-sm font-semibold text-neutral-500 dark:text-neutral-300 uppercase tracking-wide">
                        Total Cost
                    </th>
                    <th scope="col" class="relative px-3 py-4">
                        <span class="sr-only">Edit</span>
                    </th>
                </tr>
            </thead>
            <tbody class="divide-y divide-neutral-200 dark:divide-neutral-700">
                @foreach($transactions as $transaction)
                    <tr @if($loop->odd) class="bg-neutral-100 dark:bg-neutral-600" @endif>
                        <td class="px-6 py-4 whitespace-nowrap">
                            <p class="font-semibold text-lg text-neutral-600 dark:text-neutral-300">
                                {{ $transaction->buy_date->format('jS M Y') }}
                            </p>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap text-right">
                            <p class="text-neutral-500 dark:text-neutral-400">
                                &pound;{{ number_format($transaction->buy_price, 2) }}
                            </p>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap text-right">
                            <p class="text-neutral-500 dark:text-neutral-400">
                                {{ number_format($transaction->quantity, 2) }}
                            </p>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap text-right">
                            <p class="font-medium text-neutral-600 dark:text-neutral-300">
                                &pound;{{ number_format($transaction->total_cost, 2) }}
                            </p>
                        </td>
                        <td class="px-3 py-4 whitespace-nowrap text-right">
                            @if (isset($mode) && $mode == 'edit')
                                <a href="{{ route('transaction.edit', ['id' => $transaction->id]) }}" class="px-3 py-2 rounded-md text-sm font-medium text-neutral-500 hover:bg-neutral-200 dark:hover:bg-neutral-800 dark:text-neutral-300">Edit</a>
                            @else
                                <a href="{{ route('transaction.view', ['id' => $transaction->id]) }}" class="px-3 py-2 rounded-md text-sm font-medium text-neutral-500 hover:bg-neutral-200 dark:hover:bg-neutral-800 dark:text-neutral-300">View</a>
                            @endif
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <div class="grid gap-4 block md:hidden">
        @foreach($transactions as $transaction)
            @include('includes.cards.small', [
                'title' => $transaction->buy_date->format('jS M Y'),
                'subtitle' => '£' . number_format($transaction->buy_price, 2),
                'price' => number_format($transaction->total_cost, 2),
                'link' => route('transaction.' . (isset($mode) && $mode == 'edit' ? 'edit' : 'view'), ['id' => $transaction->id]),
                'colour' => $symbol->portfolio->colour,
                'belongsTo' => $transaction->id,
            ])
        @endforeach
    </div>
</div>